### ISSUE TITLE
Crash "Attempted to add a constraint that requires recomputing concolic values"

### ISSUE THREAD

**Issue by vitalych** [S2E/s2e-env#335]
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x000015554cb18801 in __GI_abort () at abort.c:79
#2  0x0000155550e4f8cc in klee::Executor::fork (this=0x5555568a3800, current=..., condition_=..., keepConditionTrueInCurrentState=false) at /home/vitaly/s2e/s2e/klee/lib/Core/Executor.cpp:482
#3  0x0000155550d193e9 in s2e::S2EExecutor::fork (this=0x5555568a3800, current=..., condition=..., keepConditionTrueInCurrentState=false) at /home/vitaly/s2e/s2e/libs2ecore/src/S2EExecutor.cpp:1437
#4  0x0000155550e542f4 in klee::Executor::executeInstruction (this=0x5555568a3800, state=..., ki=0x5555577df8e0) at /home/vitaly/s2e/s2e/klee/lib/Core/Executor.cpp:841
#5  0x0000155550d1e146 in s2e::S2EExecutor::executeInstructions (this=0x5555568a3800, state=0x1555299780f0, callerStackSize=1) at /home/vitaly/s2e/s2e/libs2ecore/src/S2EExecutor.cpp:1055
#6  0x0000155550d17e50 in s2e::S2EExecutor::executeTranslationBlockKlee (this=0x5555568a3800, state=0x1555299780f0, tb=0x1555160b2828) at /home/vitaly/s2e/s2e/libs2ecore/src/S2EExecutor.cpp:1186
#7  0x0000155550d1844f in s2e::S2EExecutor::executeTranslationBlock (this=0x5555568a3800, state=0x1555299780f0, tb=0x1555160b2828) at /home/vitaly/s2e/s2e/libs2ecore/src/S2EExecutor.cpp:1287
#8  0x0000155550d1808f in s2e::S2EExecutor::executeTranslationBlockSlow (env1=0x155528000cd0, tb=0x1555160b2828) at /home/vitaly/s2e/s2e/libs2ecore/src/S2EExecutor.cpp:1216
#9  0x0000155550d110da in s2e::S2EExecutor::executeTranslationBlockFast (env1=0x155528000cd0, tb=0x1555160b2828) at /home/vitaly/s2e/s2e/libs2ecore/src/S2EExecutor.cpp:1237
#10 0x0000155550d714d1 in fetch_and_run_tb (prev_tb=0, env=0x155528000cd0) at /home/vitaly/s2e/s2e/libcpu/src/cpu-exec.c:238
#11 0x0000155550d70dde in execution_loop (env=0x155528000cd0) at /home/vitaly/s2e/s2e/libcpu/src/cpu-exec.c:407
#12 0x0000155550d70b1f in cpu_x86_exec (env=0x155528000cd0) at /home/vitaly/s2e/s2e/libcpu/src/cpu-exec.c:482
#13 0x0000155550a7ce79 in s2e::kvm::VCPU::coroutineFcn (opaque=0x155528000b20) at /home/vitaly/s2e/s2e/libs2e/src/s2e-kvm-vcpu.cpp:251
#14 0x0000155552b79a7e in coroutine_trampoline (i0=671546672, i1=5461) at /home/vitaly/s2e/s2e/libcoroutine/src/coroutine-ucontext.c:117
#15 0x000015554cb306b0 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#16 0x0000155531965b80 in ?? ()
#17 0x0000000000000000 in ?? ()
```

**Comment by vitalych** [comment]
[test-fuzzer-withoutprintf.tar.xz.zip](https://github.com/S2E/s2e-env/files/3880683/test-fuzzer-withoutprintf.tar.xz.zip)

**Comment by vitalych** [comment]
This does not reproduce anymore on `issue/269-upgrade`

**Comment by vitalych** [comment]
There is probably a bug in the solver builder:
https://github.com/S2E/klee/blob/master/lib/Solver/Z3Builder.cpp#L152
Sign extending a 1-bit bool value should return 0xff... if the bit is one.
