### ISSUE TITLE
MemoryMapRegionType Assertion `end > addr' failed

### ISSUE THREAD

**Issue by xdxdxdx** [S2E/s2e-env#403]
The test program is a CTF binary with 6 menu options, and the size of the malloc is determined by the user.

I want to know how S2E handles when the parameter of malloc is a symbol variable. So, in my plugin, I excluded other option paths and tried to print the contents of the heap when the program executed to 0xadf (the instruction after 'call _malloc').

In input.so, I overwrite the read function and store it in the guest-tools64 directory.

```
.text:0000000000000AC0 add_page        proc near               ; CODE XREF: main+82↑p
.text:0000000000000AC0 ; __unwind {
.text:0000000000000AC0                 push    rbx
.text:0000000000000AC1                 lea     rdi, aHowManyCharact ; "How many characters is this page?"
.text:0000000000000AC8                 call    _puts
.text:0000000000000ACD                 xor     eax, eax
.text:0000000000000ACF                 call    get_choice
.text:0000000000000AD4                 mov     rdi, rax        ; size
.text:0000000000000AD7                 mov     rbx, rax
.text:0000000000000ADA                 call    _malloc
.text:0000000000000ADF                 mov     rcx, cs:curr_page
.text:0000000000000AE6                 lea     rdx, pages
.text:0000000000000AED                 mov     rdi, rbx        ; nbytes
.text:0000000000000AF0                 mov     [rdx+rcx*8], rax
.text:0000000000000AF4                 pop     rbx
.text:0000000000000AF5                 jmp     set_page
.text:0000000000000AF5 add_page        endp
```

After running, the program has the following error.
```
26 [State 160] LinuxMonitor: mmap pid=0x4e5 addr=0xfffffffffffffff4 size=0x8000000000001000 prot=0x3 flag=0x22 pgoff=0x0
qemu-system-x86_64: /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Support/MemoryMap.cpp:112: void s2e::plugins::(anonymous namespace)::MemoryMapRegionManager::addRegion(uint64_t, uint64_t, uint64_t, s2e::plugins::MemoryMapRegionType): Assertion `end > addr' failed.
./launch-s2e.sh: line 92: 81171 Aborted                 (core dumped) LD_PRELOAD=$LIBS2E $QEMU $QEMU_DRIVE -k en-us $GRAPHICS -monitor null -m $QEMU_MEMORY -enable-kvm -serial file:serial.txt $QEMU_EXTRA_FLAGS -loadvm $QEMU_SNAPSHOT $*
```

**Comment by vitalych** [comment]
Thanks! Please run S2E in gdb (launch-s2e.sh debug) and paste the stack trace of the crash.

**Comment by vitalych** [comment]
Please also attach the xz file. Github won't like it, so you can put it in  zip.

**Comment by xdxdxdx** [comment]
Here are some error messages and stack traces. The zip includes custom plugins and .so needed for operation. Thank you！
```
132 [State 138] LinuxMonitor: mmap pid=0x4e8 addr=0xfffffffffffffff4 size=0x8000000000001000 prot=0x3 flag=0x22 pgoff=0x0
qemu-system-x86_64: /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Support/MemoryMap.cpp:112: void s2e::plugins::(anonymous namespace)::MemoryMapRegionManager::addRegion(uint64_t, uint64_t, uint64_t, s2e::plugins::MemoryMapRegionType): Assertion `end > addr' failed.

Thread 5 "qemu-system-x86" received signal SIGABRT, Aborted.
[Switching to Thread 0x155545e36700 (LWP 36556)]

[----------------------------------registers-----------------------------------]
RAX: 0x0 
RBX: 0x1554c1ad1000 --> 0x756d657100001000 
RCX: 0x15554f555428 (<__GI_raise+56>:	cmp    rax,0xfffffffffffff000)
RDX: 0x6 
RSI: 0x8ecc 
RDI: 0x8ec3 
RBP: 0x155553b38cd5 ("end > addr")
RSP: 0x1555034c2138 --> 0x15554f55702a (<__GI_abort+362>:	mov    rdx,QWORD PTR fs:0x10)
RIP: 0x15554f555428 (<__GI_raise+56>:	cmp    rax,0xfffffffffffff000)
R8 : 0x1554bf1a5730 --> 0x1554beee6720 --> 0x130 
R9 : 0x1 
R10: 0x8 
R11: 0x206 
R12: 0x70 ('p')
R13: 0x155553b38ce0 ("void s2e::plugins::(anonymous namespace)::MemoryMapRegionManager::addRegion(uint64_t, uint64_t, uint64_t, s2e::plugins::MemoryMapRegionType)")
R14: 0x155545e369c0 --> 0x1555460379c0 --> 0x155546c399c0 --> 0x155546e3a9c0 --> 0x15554fb02260 (0x0000155545e369c0)
R15: 0x0
EFLAGS: 0x206 (carry PARITY adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x15554f55541e <__GI_raise+46>:	mov    eax,0xea
   0x15554f555423 <__GI_raise+51>:	movsxd rdi,ecx
   0x15554f555426 <__GI_raise+54>:	syscall 
=> 0x15554f555428 <__GI_raise+56>:	cmp    rax,0xfffffffffffff000
   0x15554f55542e <__GI_raise+62>:	ja     0x15554f555450 <__GI_raise+96>
   0x15554f555430 <__GI_raise+64>:	repz ret 
   0x15554f555432 <__GI_raise+66>:	nop    WORD PTR [rax+rax*1+0x0]
   0x15554f555438 <__GI_raise+72>:	test   ecx,ecx
[------------------------------------stack-------------------------------------]
0000| 0x1555034c2138 --> 0x15554f55702a (<__GI_abort+362>:	mov    rdx,QWORD PTR fs:0x10)
0008| 0x1555034c2140 --> 0x20 (' ')
0016| 0x1555034c2148 --> 0x0 
0024| 0x1555034c2150 --> 0x0 
0032| 0x1555034c2158 --> 0x0 
0040| 0x1555034c2160 --> 0x0 
0048| 0x1555034c2168 --> 0x0 
0056| 0x1555034c2170 --> 0x0 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGABRT
0x000015554f555428 in __GI_raise (sig=sig@entry=0x6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
gdb-peda$ back
#0  0x000015554f555428 in __GI_raise (sig=sig@entry=0x6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x000015554f55702a in __GI_abort () at abort.c:89
#2  0x000015554f54dbd7 in __assert_fail_base (fmt=<optimized out>, 
    assertion=assertion@entry=0x155553b38cd5 "end > addr", 
    file=file@entry=0x155553b351a1 "/home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Support/MemoryMap.cpp", 
    line=line@entry=0x70, 
    function=function@entry=0x155553b38ce0 "void s2e::plugins::(anonymous namespace)::MemoryMapRegionManager::addRegion(uint64_t, uint64_t, uint64_t, s2e::plugins::MemoryMapRegionType)") at assert.c:92
#3  0x000015554f54dc82 in __GI___assert_fail (
    assertion=0x155553b38cd5 "end > addr", 
    file=0x155553b351a1 "/home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Support/MemoryMap.cpp", line=0x70, 
    function=0x155553b38ce0 "void s2e::plugins::(anonymous namespace)::MemoryMapRegionManager::addRegion(uint64_t, uint64_t, uint64_t, s2e::plugins::MemoryMapRegionType)") at assert.c:101
#4  0x00001555514de2a6 in s2e::plugins::(anonymous namespace)::MemoryMapRegionManager::addRegion (this=0x1554bd3bccf8, pid=0x4e8, addr=0xfffffffffffff000, 
    end=0x8000000000001000, type=0x3)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Support/MemoryMap.cpp:112
#5  0x00001555514dc131 in s2e::plugins::(anonymous namespace)::MemoryMapState::addRegion (this=0x1554bd3bccc0, pid=0x4e8, addr=0xfffffffffffff000, 
    end=0x8000000000001000, type=0x3)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Support/MemoryMap.cpp:234
#6  0x00001555514dbf5d in s2e::plugins::MemoryMap::onLinuxMemoryMap (
    this=0x555556fd75c0, state=0x15553cb023f0, pid=0x4e8, 
    addr=0xfffffffffffffff4, size=0x8000000000001000, prot=0x3)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Support/MemoryMap.cpp:387
#7  0x00001555514f6b23 in sigc::functorn<s2e::plugins::MemoryMap, void, s2e::S2EExecutionState*, unsigned long, unsigned long, unsigned long, unsigned long>::operator() (this=0x555558249940, types=0x3, types=0x3, types=0x3, types=0x3, 
    types=0x3)
    at /home/user/Downloads/s2e/source/s2e/libfsigc++/include/fsigc++/fsigc++.h:192
#8  0x00001555514970f1 in sigc::signal<void, s2e::S2EExecutionState*, unsigned long, unsigned long, unsigned long, unsigned long>::emit (this=0x5555582405c0, 
    params=0x3, params=0x3, params=0x3, params=0x3, params=0x3)
    at /home/user/Downloads/s2e/source/s2e/libfsigc++/include/fsigc++/fsigc++.h:280
#9  0x000015555149698d in s2e::plugins::LinuxMonitor::handleMemMap (
    this=0x55555823fac0, state=0x15553cb023f0, cmd=...)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Linux/LinuxMonitor.cpp:175
#10 0x0000155551496da0 in s2e::plugins::LinuxMonitor::handleCommand (
    this=0x55555823fac0, state=0x15553cb023f0, 
    guestDataPtr=0xffffc90000507e7c, guestDataSize=0x3c, _cmd=0x1555034c2630)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Linux/LinuxMonitor.cpp:225
#11 0x0000155551495197 in s2e::plugins::BaseLinuxMonitor::handleOpcodeInvocation (this=0x55555823fac0, state=0x15553cb023f0, guestDataPtr=0xffffc90000507e7c, 
    guestDataSize=0x3c)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/OSMonitors/Linux/BaseLinuxMonitor.h:162
#12 0x000015555141222a in s2e::plugins::BaseInstructions::invokePlugin (
    this=0x555557667300, state=0x15553cb023f0)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/Core/BaseInstructions.cpp:570
#13 0x0000155551413fcf in s2e::plugins::BaseInstructions::handleBuiltInOps (
    this=0x555557667300, state=0x15553cb023f0, opcode=0xb00)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/Core/BaseInstructions.cpp:835
#14 0x000015555140f35b in s2e::plugins::BaseInstructions::onCustomInstruction (
    this=0x555557667300, state=0x15553cb023f0, opcode=0xb00)
    at /home/user/Downloads/s2e/source/s2e/libs2eplugins/src/s2e/Plugins/Core/BaseInstructions.cpp:983
#15 0x000015555142022b in sigc::functorn<s2e::plugins::BaseInstructions, void, s2e::S2EExecutionState*, unsigned long>::operator() (this=0x555558248470, 
    types=0xb00, types=0xb00)
    at /home/user/Downloads/s2e/source/s2e/libfsigc++/include/fsigc++/fsigc++.h:192
#16 0x00001555514160e1 in sigc::signal<void, s2e::S2EExecutionState*, unsigned long>::emit (this=0x5555570214e0, params=0xb00, params=0xb00)
    at /home/user/Downloads/s2e/source/s2e/libfsigc++/include/fsigc++/fsigc++.h:280
#17 0x000015555171b90d in s2e_tcg_custom_instruction_handler (arg=0xb00)
    at /home/user/Downloads/s2e/source/s2e/libs2ecore/src/CorePluginInterface.cpp:80
#18 0x00001555280c7741 in ?? ()
#19 0x00001555034c2a50 in ?? ()
#20 0x00001555517d7b07 in tcg_out_sib_offset (s=0x36eb5, r=0x1555, 
    rm=0x3c0008c0, index=0x0, shift=0x0, offset=0x1555514067c0)
    at /home/user/Downloads/s2e/source/s2e/libtcg/src/i386/tcg-target.inc.c:716
#21 0xffffc90000507e7c in ?? ()
#22 0x000000000000003c in ?? ()
#23 0xffffc90000507eb8 in ?? ()
#24 0xffffc90000507e50 in ?? ()
#25 0xffffc90000507ee0 in ?? ()
#26 0xffffc90000507e7c in ?? ()
#27 0xffffc90000507eb8 in ?? ()
#28 0xfffffffffffffff4 in ?? ()
#29 0x0000000000000000 in ?? ()
```
[newton.zip](https://github.com/S2E/s2e-env/files/4529694/newton.zip)

**Comment by qinkunbao** [comment]
Hi,

I ran into the same problem when I analyzed some simple sgx programs (Simulation Mode). May I ask if you have any update on it?
