### ISSUE TITLE
./test.sh failed with module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by yh570** [S2E/s2e-env#421]
Hi, I just installed s2e-env and I'd like to try with the test.sh, but I got the error message as the title. I followed by the closed issues with the same problem and I uninstall the enum34, but the error message is not changed, which is shown below:

```
Collecting iniconfig
  Using cached iniconfig-1.1.1.tar.gz (8.1 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/yh570/s2e-env/venv-test/bin/python3 /home/yh570/s2e-env/venv-test/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zboagqt2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.2.0' wheel 'setuptools_scm>3'
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/yh570/s2e-env/venv-test/lib/python3.7/site-packages/pip/__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/home/yh570/s2e-env/venv-test/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/usr/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/usr/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/yh570/s2e-env/venv-test/bin/python3 /home/yh570/s2e-env/venv-test/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zboagqt2/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=41.2.0' wheel 'setuptools_scm>3' Check the logs for full command output.
(venv) yh570@giantpanda:~/s2e-env$ which pip
/home/yh570/s2e-env/venv/bin/pip
(venv) yh570@giantpanda:~/s2e-env$ pip freeze | grep enum34
(venv) yh570@giantpanda:~/s2e-env$ 
```

Woudl you please give me some suggestions to solve the problem? Thank you.

**Comment by yh570** [comment]
Ahhh I just solved this problem... I added 'pip uninstall -y enum34' in test.sh before the script install the pylint, and now test.sh works perfectly...

**Comment by vitalych** [comment]
`enum34` is in the list of dependencies in setup.py, maybe it could be removed if it's not needed. I can't find this module imported anywhere.

**Comment by yh570** [comment]
Hmmm I just tried to run s2e with coreutils, and I found the environment is requiring enum34 which makes me confused. The error message is shown below:

```
(venv) yh570@giantpanda:~/s2e-env/experiment$ s2e new_project --image debian-9.2.1-i386 /home/yh570/scripts/fuzz/cat/coreutils-6.10/src/cat /etc/fstab
Traceback (most recent call last):
  File "/home/yh570/s2e-env/venv/bin/s2e", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/yh570/s2e-env/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/yh570/s2e-env/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/yh570/s2e-env/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/yh570/s2e-env/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/yh570/s2e-env/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/yh570/s2e-env/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34' distribution was not found and is required by s2e-env
```

**Comment by vitalych** [comment]
You may need to remove it from setup.py and rerun the installation (pip install -e .).

**Comment by yh570** [comment]
@vitalych thank you for your suggestions, I solved this problem by recompile s2e. But I met another problem when building the s2e environment. The error message is shown below:

```
[S2E:s2e] (venv) yh570@giantpanda:~/s2e$ s2e build
INFO: [build] Building S2E (release) in /home/yh570/s2e/build
make: Entering directory '/home/yh570/s2e/build'
INFO: [sh.command] <Command '/usr/bin/make --directory=/home/yh570/s2e/build --file=/home/yh570/s2e/source/Makefile install', pid 29455>: process started
/home/yh570/s2e/source/scripts//..//s2e/Makefile:83: *** "Failed to determine Clang binary to download: Linux distro Debian GNU/Linux is not supported".  Stop.
make: Leaving directory '/home/yh570/s2e/build'
ERROR: [build] 

  RAN: /usr/bin/make --directory=/home/yh570/s2e/build --file=/home/yh570/s2e/source/Makefile install

  STDOUT:


  STDERR:


```

After reading the `Makefile` and `determine_clang_binary_suffix.py`, I found it looks like s2e is not supported Linux distro Debian(I hope I'm wrong...), my debian version is shown below:

```
[S2E:s2e] (venv) yh570@giantpanda:~/s2e$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10.6 (buster)
Release:        10.6
Codename:       buster

```
Would you give me some suggestion about this issue? Thank you again for your help.

**Comment by vitalych** [comment]
S2E does not support Debian, only Ubuntu (pretty much because I only use Ubuntu). Adding support shouldn't be hard, since both distributions are similar. You will need to:
1. Update https://github.com/S2E/s2e/blob/master/scripts/determine_clang_binary_suffix.py
2. If needed, update package lists in https://github.com/S2E/s2e-env/blob/master/s2e_env/dat/config.yaml#L29
