### ISSUE TITLE
`s2e new_plugin InstructionTracker` fails

### ISSUE THREAD

**Issue by qinkunbao** [S2E/s2e-env#431]
I am following the document from `http://s2e.systems/docs/Howtos/WritingPlugins.html`. I got the following error messages.

OS: Ubuntu 20
s2e-env version: 8f6eb55d38053b4aead237304f8c9a6e76d7c067

INFO: [new_plugin] Creating plugin in /home/s2e/s2e/s2e/source/s2e/libs2eplugins/src/s2e/Plugins
Traceback (most recent call last):
  File "/home/s2e/s2e/s2e-env/venv/bin/s2e", line 11, in <module>
    load_entry_point('s2e-env==0.20', 'console_scripts', 's2e')()
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/s2e_env/manage.py", line 190, in main
    manager.execute()
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/s2e_env/manage.py", line 179, in execute
    self.fetch_command(subcommand).run_from_argv(self._argv)
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/s2e_env/command.py", line 154, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/s2e_env/command.py", line 176, in execute
    self.handle(*args, **options)
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/s2e_env/commands/new_plugin.py", line 136, in handle
    render_template(context, 'plugin.cpp.template', cpp_plugin_path, templates_dir)
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/s2e_env/utils/templates.py", line 72, in render_template
    rendered_data = env.get_template(template).render(context)
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/s2e/s2e/s2e-env/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: plugin.cpp.template
[S2E:s2e] (venv) FAIL: 1

**Comment by vitalych** [comment]
I could not reproduce this error. Could you try https://github.com/S2E/s2e-env/pull/432? It has better logging around the place that threw the exception.

**Comment by qinkunbao** [comment]
OK. Thanks for your reply. Here is what I got.

[S2E:s2e] (venv) s2e➜  s2e-env : issue/xxx-newplugin ✔ : ᐅ  s2e new_plugin InstructionTracker
INFO: [new_plugin] Creating plugin in /home/s2e/s2e_new/s2e/source/s2e/libs2eplugins/src/s2e/Plugins
Traceback (most recent call last):
  File "/home/s2e/s2e_new/s2e-env/venv/bin/s2e", line 11, in <module>
    load_entry_point('s2e-env==0.20', 'console_scripts', 's2e')()
  File "/home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/manage.py", line 190, in main
    manager.execute()
  File "/home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/manage.py", line 179, in execute
    self.fetch_command(subcommand).run_from_argv(self._argv)
  File "/home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/command.py", line 154, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/command.py", line 176, in execute
    self.handle(*args, **options)
  File "/home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/commands/new_plugin.py", line 136, in handle
    render_template(context, 'plugin.cpp.template', cpp_plugin_path, templates_dir)
  File "/home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/utils/templates.py", line 73, in render_template
    env = _init_template_env(templates_dir)
  File "/home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/utils/memoize.py", line 49, in __call__
    value = self._func(*args)
  File "/home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/utils/templates.py", line 53, in _init_template_env
    raise Exception(f'Directory {templates_dir} does not exist')
Exception: Directory /home/s2e/s2e_new/s2e-env/venv/lib/python3.8/site-packages/s2e_env/commands/plugin_creation does not exist

**Comment by vitalych** [comment]
It should work now.
