### ISSUE TITLE
Can't download PDB with symchk

### ISSUE THREAD

**Issue by vitalych** [S2E/s2e-env#72]
```
$ ../scripts/symchk.py  en_windows_xp_professional_with_service_pack_3_x86_cd_x14-80428_40f8880122a030a7e9e1fedea833b33d_ntkrnlmp.exe
Unpacking to en_windows_xp_professional_with_service_pack_3_x86_cd_x14-80428_40f8880122a030a7e9e1fedea833b33d_ntkrnlmp.pdb
Traceback (most recent call last):
  File "../scripts/symchk.py", line 208, in <module>
    main()
  File "../scripts/symchk.py", line 204, in main
    handle_pe(args.exe, not args.verbose)
  File "../scripts/symchk.py", line 173, in handle_pe
    unpack_file(saved_file, new_file)
  File "../scripts/symchk.py", line 182, in unpack_file
    Archive(source).extractall(dirname)
  File "/c/Users/Vitaly/Cyberhaven/guest-tools/windows/venv/lib/python2.7/site-packages/pyunpack/__init__.py", line 90, in extractall
    self.extractall_patool(directory, patool_path)
  File "/c/Users/Vitaly/Cyberhaven/guest-tools/windows/venv/lib/python2.7/site-packages/pyunpack/__init__.py", line 62, in extractall_patool
    raise PatoolError('patool can not unpack\n' + str(p.stderr))
pyunpack.PatoolError: patool can not unpack
patool error: error extracting /c/Users/Vitaly/Cyberhaven/guest-tools/windows/kernels/ntkrnlmp.pd_: unknown archive format for file `/c/Users/Vitaly/Cyberhaven/guest-tools/windows/kernels/ntkrnlmp.pd_'
```

**Comment by adrianherrera** [comment]
Yup, I got this two when I tried to regenerate the header file to include
the process return code. If I remember correctly ntkrnlmp.pd_ is an empty
file, which is why symcheck bombs out.

I have no idea how to fix this :/
